build:
	just bison && just lex && just compile && just run
run: 
	cat test  && ./parser < test
lex:
	flex  lexer.l 
compile:
	clang++ -o parser scanner.cpp  Parser.cpp -fsanitize=address
bison:
	bison  parser.y
@cleanup:
	rm -rf *.tab.* *.yy.* *.output parser *.cpp *.hpp
